
services:
  nats-servers:
    container_name: nats-servers
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: always
  
  order-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb

  client-gateway:
    container_name: client-gateway
    depends_on:
      - nats-servers
    build: ./client-gateway #proceso de contruccion de la imagen esta en el client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-servers:4222
  
  products-ms:
    container_name: products-ms
    depends_on:
      - nats-servers
    build: ./products-ms

    # al utilizar port en la definicion del servicio exponemos un puerto fuera de la red del contenedor con un puerto dentro del contenedor
    # la idea es que en produccion todos los servicios sean inaccessible con excepcion del client-gateway (ya que este es la puerta de entrada) y payment-ms (por el webhook) 
    # ports:
    #   - "3001:3001"
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-servers:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    container_name: orders-ms
    depends_on:
      - nats-servers
      - order-db
    build: ./orders-ms


    # al utilizar port en la definicion del servicio exponemos un puerto fuera de la red del contenedor con un puerto dentro del contenedor
    # la idea es que en produccion todos los servicios sean inaccessible con excepcion del client-gateway (ya que este es la puerta de entrada) y payment-ms (por el webhook) 
    # ports:
    #   - "3002:3002"
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-servers:4222
      - DATABASE_URL=postgresql://postgres:123456@orders_database:5432/ordersdb?schema=public
  
  payments-ms:
    container_name: payments-ms
    build: ./payments-ms

    # al utilizar port en la definicion del servicio exponemos un puerto fuera de la red del contenedor con un puerto dentro del contenedor
    # la idea es que en produccion todos los servicios sean inaccessible con excepcion del client-gateway (ya que este es la puerta de entrada) y payment-ms (por el webhook) 
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    volumes:
      - ./payments-ms/src:/usr/src/app/src 
    command: npm run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-servers:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - ENDPOINT_SECRET_TESTING=${ENDPOINT_SECRET_TESTING}
      - ENDPOINT_SECRET_OFFICIAL=${ENDPOINT_SECRET_OFFICIAL}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}

  auth-ms:
    container_name: auth-ms
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-servers:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  stripe:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    restart: unless-stopped
    tty: true            # Mantiene la terminal activa
    stdin_open: true     # Mantiene el flujo de entrada abierto
    volumes:
      - ./stripe_config:/root/.config/stripe
    # Este comando es el que evita que el contenedor se muera
    command: listen --forward-to http://host.docker.internal:${PAYMENTS_MS_PORT}/payments/webhook

# Ejecutar esto en payments-ms
# hookdeck listen 3003 stripe-to-localhost --path /payments/webhook


