
# NOTA SUPER IMPORTANTE: 
# Al hacer la contruccion de la imagen (docker compose -f docker-compose.prod.yml build)
# no se necesitan los siguiente atributos PORTS, VOLUMES, COMMAND, ENVIRONMENT
## PERO.....
# Al momento de arrancar el proyecto (docker compose -f docker-compose.prod.yml up)
# ahi si es necesario tener PORTS y ENVIRONMENT


services:
  nats-servers:
    container_name: nats-servers
    image: nats

  client-gateway:
    image: us-east4-docker.pkg.dev/tienda-microservices-505922/images-registry/client-gateway
    container_name: client-gateway-ms
    build: 
      context: ./client-gateway #proceso de contruccion de la imagen esta en el client-gateway
      dockerfile: dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
  
  products-ms:
    image: us-east4-docker.pkg.dev/tienda-microservices-505922/images-registry/products-ms
    container_name: products-ms
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${PRODUCT_DATABASE_URL}
  
  orders-ms:
    image: us-east4-docker.pkg.dev/tienda-microservices-505922/images-registry/orders-ms
    container_name: orders-ms
    build:   
      context: ./orders-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=${ORDERS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${ORDERS_DATABASE_URL}
  
  auth-ms:
    image: us-east4-docker.pkg.dev/tienda-microservices-505922/images-registry/auth-ms
    container_name: auth-ms
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=${AUTH_MS}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  payments-ms:
    image: us-east4-docker.pkg.dev/tienda-microservices-505922/images-registry/payments-ms
    container_name: payments-ms
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - ENDPOINT_SECRET_TESTING=${ENDPOINT_SECRET_TESTING}
      - ENDPOINT_SECRET_OFFICIAL=${ENDPOINT_SECRET_OFFICIAL}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}

  # stripe:
  #   image: stripe/stripe-cli:latest
  #   container_name: stripe-cli
  #   restart: unless-stopped
  #   tty: true            # Mantiene la terminal activa
  #   stdin_open: true     # Mantiene el flujo de entrada abierto
  #   volumes:
  #     - ./stripe_config:/root/.config/stripe
  #   # Este comando es el que evita que el contenedor se muera
  #   command: listen --forward-to http://host.docker.internal:${PAYMENTS_MS_PORT}/payments/webhook

# Ejecutar esto en payments-ms
# hookdeck listen 3003 stripe-to-localhost --path /payments/webhook
  